pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        gradlePluginPortal()
    }
}

include 'intellium-1.21:intellium-1.21-1.21.8'
include 'intellium-1.21:intellium-1.21.11'
include 'intellium-1.21:intellium-1.21.10'
include 'intellium-26.1'
include 'intellium-26.3'
